version: '3.9'

services:
  jupyter:
    build:
      context: ./code
      dockerfile: Dockerfile
    image: "jupyter-${PROJECT_NAME}:${TAG}"
    ports:
      - "8888:8888"
    volumes:
      - .:/app
